pages:
  image: alpine:latest
  script:
    - apt add --no-cache doxygen graphviz ttf-freefont
    - doxygen Doxyfile
    - mkdir -p public && mv html public/
  artifacts:
    paths:
      - public/
  only:
    - master